//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SHM.Models
{
	public partial class SYS_USERINFO
	{
		public SYS_USERINFO MiniItem(bool isMini = true){
			return new SYS_USERINFO(){
				ID = this.ID,
				GUID = this.GUID,
				LoginName = this.LoginName,
				PASSWORD = this.PASSWORD,
				NAME = this.NAME,
				AGE = this.AGE,
				SEX = this.SEX,
				PHONE = this.PHONE,
				DepartmentID = this.DepartmentID,
				CreateTime = this.CreateTime,
				Email = this.Email,
				QQ = this.QQ,
				Tel = this.Tel,
				Position = this.Position,
				HeadImg = this.HeadImg,
			};
		}
	}
}
